name = "DynamicFactorModels"
uuid = "769869f1-5d94-4e56-9697-b0b8d416fdb8"
authors = ["Quint Wiersma <qnt.wrsm@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
